[package]
name = "myriad"
version = "0.1.0"
authors = ["Kane Valentine <kane@cute.im>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0.27"
serde_derive = "1.0.27"
postgres = "0.15.2"
redis = "0.8.0"
envy = "0.3.2"